import { useState, useEffect, useMemo, useCallback } from 'react';
import { CaretLeft, CaretRight, Folder, Folders, Star, Devices, Books, PenNib, CaretDown, CaretRight as NextIcon, CaretLeft as PrevIcon } from '@phosphor-icons/react';
import { useLanguage } from '../../i18n/LanguageContext';
import './ProjectsWindow.css';

const projectData = {
  en: [
    { id: 1, name: 'Atomic Design System', category: 'design-systems', isFavorite: true, image: '/projects/atomic-design-system/thumbnail.png', context: 'Development of an Atomic Design-based Design System, with creation of tokens, reusable components and structuring of a React library. The project aimed to accelerate the front-end team\'s work, reduce inconsistencies between products and strengthen collaboration between design and engineering. To develop the components, MiniMax 2.5 was used in OpenCode.', link: 'https://github.com/ThiagoJezini/Web_Design_Atomic', problem: 'The design challenge was developing a scalable design system that could unify visual standards across multiple products while still being flexible enough to accommodate future needs. The goal was to reduce development time, eliminate inconsistencies, and improve collaboration between design and engineering teams through a shared component library.', role: 'Design team leader', result: 'The library was widely adopted and expanded with additional components to cover emerging project needs. Development time was significantly reduced, and visual consistency improved across all products. The system became the single source of truth for design and enabled faster iteration cycles.', lessons: 'In this project, the main learning was more technical, especially about how AI can be implemented to enhance and optimize human productivity without replacing peoples role in the process. It was an important experience to understand AI as a support tool: capable of automating steps, accelerating analyses, and facilitating decisions, but always keeping the user as a central part of the workflow.', gallery: ['/projects/atomic-design-system/slide-1.png', '/projects/atomic-design-system/slide-2.png', '/projects/atomic-design-system/slide-3.png', '/projects/atomic-design-system/slide-4.png', '/projects/atomic-design-system/slide-5.png'] },
    { id: 2, name: 'BPMS', category: 'uiux', isFavorite: false, image: '/projects/bpms/thumbnail.png', context: 'The BPMS project is aimed at digitizing the process in which it is named (Business Process Management Suite). Initially made to order, it was thought in its development to become an end product that could be used by companies in business management and internal production.', link: '', problem: 'The design challenge was creating a system capable of transforming BPMS-based production flows into clear KPIs and actionable metrics. The goal was to help the company track performance, identify bottlenecks, and understand production efficiency without overwhelming users with complex operational data. The main focus was organizing information in a way that respected the actual structure of the company processes, but that still made dashboards, indicators, and analysis tools simple enough to support quick decisions.', role: 'Product Designer and UI & UX Designer, working directly on controlling and deliveries of the development team.', result: 'The product was delivered successfully, allowing the contractor to track their KPIs more clearly and identify production bottlenecks based on data generated by the BPMS flow itself. With this, the company gained a more strategic view of the operation, facilitating performance analysis and decision-making. In addition to meeting the internal project needs, the final system was consolidated as a scalable solution and began to be offered as a product to other company clients.', lessons: 'This was the project where I had the most creative and organizational freedom, which allowed me to participate more strategically in product and process decisions. In addition to technical learning, it was an important experience to better understand how to organize demands, align expectations, and conduct work more autonomously. I also learned a lot about people management, especially about how to deal with different professional profiles. I understood that each person has their own way of working, communicating, and solving problems, and that recognizing these differences is essential to creating a healthier, more collaborative, and efficient workflow.', gallery: ['/projects/bpms/slide-1.png', '/projects/bpms/slide-2.png', '/projects/bpms/slide-3.png', '/projects/bpms/slide-4.png', '/projects/bpms/slide-5.png', '/projects/bpms/slide-6.png', '/projects/bpms/slide-7.png'] },
    { id: 3, name: 'InspectHub', category: 'uiux', isFavorite: false, image: '/projects/inspect-hub/thumbnail.png', context: 'Inspect Hub is a product focused on inspection and auditing of establishments, public services and services provided by third parties. The project emerged from similar demands from two clients, which were unified into a scalable solution designed to accommodate different contexts and be offered as a product to new clients.', link: '', problem: 'The inspection and auditing process was highly bureaucratic, involving several different stages, sectors, and leaderships. Each stakeholder had their own flows, priorities, and opinions about how other sectors work impacted theirs. The main challenge was to mediate these different views and transform the feedback received into a coherent solution, keeping the system flow clear, functional, and aligned with the needs of all involved.', role: 'Product Designer, UX Designer and Team Manager', result: 'The project was developed over 2 years, going through several validation cycles with the clients and stakeholders involved. In the end, both clients were satisfied with the solution, which helped digitize and optimize processes that were previously very manual, bureaucratic, dependent on paper and informal data requests. With the continuity of contracts and the need for new specific modules for each operation, the two projects were consolidated into a single flow, giving rise to the final product presented in this portfolio.', lessons: 'For personal development, this was an important project to learn how to deal with expectations at different levels: from clients who needed quick answers and from a team pressured to deliver the most stable solution possible in little time. Besides the design flow, I learned to better manage activities, deliverables, and communication, understanding what needed to be aligned with the team, what should be taken to the client, and how to communicate decisions clearly in a complex project.', gallery: ['/projects/inspect-hub/slide-1.png', '/projects/inspect-hub/slide-2.png', '/projects/inspect-hub/slide-3.png', '/projects/inspect-hub/slide-4.png', '/projects/inspect-hub/slide-5.png', '/projects/inspect-hub/slide-6.png', '/projects/inspect-hub/slide-7.png'] },
    { id: 4, name: 'FemtoLab', category: 'branding', isFavorite: false, image: '/projects/femtolab/thumbnail.png', context: 'Femtolab was a branding project developed in collaboration with another designer to create a complete visual identity for a university research laboratory. The goal was to translate the labs focus, values, and academic environment into a clear, consistent, and recognizable brand system. The project included the development of the brand concept, logo, visual language, color palette, typography, iconography, and brand applications, creating an identity that could represent the laboratory across different communication materials and institutional contexts.', link: '', problem: 'Femtolab had a very close-knit relationship with its members, so the identity needed to represent more than the laboratorys research field. It also had to reflect the people who were part of it, their perspectives, and the collaborative environment that shaped the labs culture. Another important challenge was aligning the expectations of the three lead professors, who had different views on what the laboratory was at that moment and what it should become in the future. Because of that, the visual identity needed to balance multiple directions at once: it had to feel technological, stay connected to nature, and still represent the members of the lab in a way that felt authentic to everyone involved.', role: 'Brand designer alongside a partner', result: 'After months of interviews and research, we decided that the laboratorys identity should embrace the natural aspect of the Rio Negro, one of the main symbols of Manaus and the Amazon region. We used the flow and movement of water as a central visual reference, combining it with sharp, angular shapes to connect the identity to technology, innovation, and the future. The final result was very well received by the three lead professors and had strong acceptance among the lab members. Over time, Femto became more than just the name of the laboratory: it started being used affectionately as a prefix for everything created within that identity, reinforcing the sense of belonging and recognition around the brand.', lessons: 'This project taught me a lot about user research and the importance of listening carefully before making design decisions. Through interviews, feedback sessions, and research with the lab members, I learned how to better understand different perspectives and translate them into a visual direction that made sense for the group. I also developed a stronger understanding of qualitative and quantitative research, how to mediate different opinions, and how to apply design theories in a real project context. It was an important experience for connecting research, concept development, and visual execution in a more intentional way.', gallery: ['/projects/femtolab/slide-1.png', '/projects/femtolab/slide-2.png', '/projects/femtolab/slide-3.png', '/projects/femtolab/slide-4.png', '/projects/femtolab/slide-5.png', '/projects/femtolab/slide-6.png', '/projects/femtolab/slide-7.png', '/projects/femtolab/slide-8.png'] },
  ],
  pt: [
    { id: 1, name: 'Atomic Design System', category: 'design-systems', isFavorite: true, image: '/projects/atomic-design-system/thumbnail.png', context: 'Development of an Atomic Design-based Design System, with creation of tokens, reusable components and structuring of a React library. The project aimed to accelerate the front-end team\'s work, reduce inconsistencies between products and strengthen collaboration between design and engineering. To develop the components, MiniMax 2.5 was used in OpenCode.', link: 'https://github.com/ThiagoJezini/Web_Design_Atomic', problem: 'O desafio de design foi desenvolver um design system escalável que pudesse unificar os padrões visuais entre múltiplos produtos, mas que ainda fosse flexível o bastante para acomodar necessidades futuras. O objetivo era reduzir o tempo de desenvolvimento, eliminar inconsistências e melhorar a colaboração entre as equipes de design e engenharia através de uma biblioteca de componentes compartilhada.', role: 'Líder da equipe de design', result: 'A biblioteca foi amplamente adotada e expandida com componentes adicionais para cobrir as necessidades dos projetos que surgiram. O tempo de desenvolvimento foi significativamente reduzido e a consistência visual melhorou em todos os produtos. O sistema se tornou a única fonte de verdade para design e permitiu ciclos de iteração mais rápidos.', lessons: 'In this project, the main learning was more technical, especially about how AI can be implemented to enhance and optimize human productivity without replacing peoples role in the process. It was an important experience to understand AI as a support tool: capable of automating steps, accelerating analyses, and facilitating decisions, but always keeping the user as a central part of the workflow.', gallery: ['/projects/atomic-design-system/slide-1.png', '/projects/atomic-design-system/slide-2.png', '/projects/atomic-design-system/slide-3.png', '/projects/atomic-design-system/slide-4.png', '/projects/atomic-design-system/slide-5.png'] },
    { id: 2, name: 'BPMS', category: 'uiux', isFavorite: false, image: '/projects/bpms/thumbnail.png', context: 'O projeto BPMS é voltado para digitalizar o processo na qual é nomeado (Business Process Management Suite). Inicialmente feito sob encomenda, foi pensado em seu desenvolvimento a tornar-se um produto final que pudesse ser utilizado por empresas no gerenciamento de negócios e produção interna.', link: '', problem: 'O desafio de design foi criar um sistema capaz de transformar os fluxos de produção baseados em BPMS em KPIs claros e métricas acionáveis. O objetivo era ajudar a empresa a acompanhar performance, identificar gargalos e entender a eficiência da produção sem sobrecarregar os usuários com dados operacionais complexos. O foco principal foi organizar as informações de uma forma que respeitasse a estrutura real dos processos da empresa, mas que ainda tornasse dashboards, indicadores e ferramentas de análise simples o suficiente para apoiar decisões rápidas.', role: 'Product Designer e UI & UX Designer, trabalhando diretamente no controle de atividades e entregas do time de desenvolvimento.', result: 'O produto foi entregue com sucesso, permitindo que o contratante acompanhasse seus KPIs com mais clareza e identificasse gargalos de produção com base nos dados gerados pelo próprio fluxo BPMS. Com isso, a empresa passou a ter uma visão mais estratégica da operação, facilitando a análise de desempenho e a tomada de decisão. Além de atender às necessidades internas do projeto, o sistema final se consolidou como uma solução escalável e passou a ser oferecido como produto para outros clientes da empresa.', lessons: 'Esse foi o projeto em que tiver mais liberdade criativa e organizacional, o que me permitiu participar de forma mais estratégica das decisões de produto e processo. Além do aprendizado técnico, foi uma experiência importante para entender melhor como organizar demandas, alinhar expectativas e conduzir o trabalho de forma mais autônoma. Também aprendi muito sobre gestão de pessoas, principalmente sobre como lidar com diferentes perfis profissionais. Entendi que cada pessoa tem sua própria forma de trabalhar, se comunicar e resolver problemas, e que reconhecer essas diferenças é essencial para criar um fluxo de trabalho mais saudável, colaborativo e eficiente.', gallery: ['/projects/bpms/slide-1.png', '/projects/bpms/slide-2.png', '/projects/bpms/slide-3.png', '/projects/bpms/slide-4.png', '/projects/bpms/slide-5.png', '/projects/bpms/slide-6.png', '/projects/bpms/slide-7.png'] },
    { id: 3, name: 'InspectHub', category: 'uiux', isFavorite: false, image: '/projects/inspect-hub/thumbnail.png', context: 'O Inspect Hub é um produto voltado para inspeção e auditoria de estabelecimentos, órgãos públicos e serviços prestados por terceiros. O projeto surgiu a partir de demandas similares de dois clientes, que foram unificadas em uma solução escalável, pensada para atender diferentes contextos e ser oferecida como produto para novos clientes.', link: '', problem: 'O processo de inspeção e auditoria era altamente burocrático, envolvendo várias etapas, setores e lideranças diferentes. Cada stakeholder tinha seus próprios fluxos, prioridades e opiniões sobre como o trabalho dos outros setores impactava o seu. O principal desafio foi mediar essas diferentes visões e transformar os feedbacks recebidos em uma solução coerente, mantendo o fluxo do sistema claro, funcional e alinhado às necessidades de todos os envolvidos.', role: 'Product Designer, UX Designer e Gestor da Equipe', result: 'O projeto foi desenvolvido ao longo de 2 anos, passando por diversos ciclos de validação com os clientes e stakeholders envolvidos. Ao final, ambos os clientes ficaram satisfeitos com a solução, que ajudou a digitalizar e otimizar processos antes muito manuais, burocráticos, dependentes de papel e de solicitações informais de dados. Com a continuidade dos contratos e a necessidade de novos módulos específicos para cada operação, os dois projetos foram consolidados em um fluxo único, dando origem ao produto final apresentado neste portfólio.', lessons: 'Para o meu desenvolvimento pessoal, esse foi um projeto importante para aprender a lidar com expectativas em diferentes níveis: de clientes que precisavam de respostas rápidas e de um time pressionado a entregar a solução mais estável possível em pouco tempo. Além do fluxo de design, aprendi a gerenciar melhor atividades, entregas e comunicação, entendendo o que precisava ser alinhado com o time, o que deveria ser levadio ao cliente e como comunicar decisões de forma clara em um projeto complexo.', gallery: ['/projects/inspect-hub/slide-1.png', '/projects/inspect-hub/slide-2.png', '/projects/inspect-hub/slide-3.png', '/projects/inspect-hub/slide-4.png', '/projects/inspect-hub/slide-5.png', '/projects/inspect-hub/slide-6.png', '/projects/inspect-hub/slide-7.png'] },
    { id: 4, name: 'FemtoLab', category: 'branding', isFavorite: false, image: '/projects/femtolab/thumbnail.png', context: 'Femtolab foi um projeto de branding desenvolvido em colaboração com outro designer para criar uma identidade visual completa para um laboratório de pesquisa universitária. O objetivo era traduzir o foco do laboratório, valores e ambiente acadêmico em um sistema de marca claro, consistente e reconhecível. O projeto incluiu o desenvolvimento do conceito da marca, logo, linguagem visual, paleta de cores, tipografia, iconografia e aplicações da marca, criando uma identidade que poderia representar o laboratório em diferentes materiais de comunicação e contextos institucionais.', link: '', problem: 'Femtolab tinha um relacionamento muito próximo com seus membros, então a identidade precisava representar mais do que apenas o campo de pesquisa do laboratório. Também precisava refletir as pessoas que faziam parte dele, suas perspectivas e o ambiente colaborativo que moldou a cultura do laboratório. Outro desafio importante era alinhar as expectativas dos três professores principais, que tinham diferentes visões sobre o que o laboratório era naquele momento e no que deveria se tornar no futuro. Por isso, a identidade visual precisava equilibrar múltiplas direções ao mesmo tempo: precisava parecer tecnológica, manter-se conectada à natureza e ainda representar os membros do laboratório de uma forma que parecesse autêntica para todos os envolvidos.', role: 'Designer de marca ao lado de um parceiro', result: 'Após meses de entrevistas e pesquisas, sentimos que a identidade do laboratório deveria abraçar o aspecto natural do Rio Negro, um dos principais símbolos de Manaus e da região amazônica. Usamos o fluxo e movimento da água como referência visual central, combinando com formas afiadas e angulares para conectar a identidade à tecnologia, inovação e o futuro. O resultado final foi muito bem recebido pelos três professores principais e teve forte aceitação entre os membros do laboratório. Com o tempo, Femto se tornou mais do que apenas o nome do laboratório: começou a ser usado com carinho como prefixo para tudo criado dentro daquela identidade, reforçando o senso de pertencimento e reconhecimento em torno da marca.', lessons: 'Este projeto me ensinou muito sobre pesquisa de usuário e a importância de ouvir com atenção antes de tomar decisões de design. Através de entrevistas, sessões de feedback e pesquisas com os membros do laboratório, aprendi a entender melhor diferentes perspectivas e traduzi-las em uma direção visual que fizesse sentido para o grupo. Também desenvolvi uma compreensão mais forte de pesquisa qualitativa e quantitativa, como mediar diferentes opiniões e como aplicar teorias de design em um contexto de projeto real. Foi uma experiência importante para conectar pesquisa, desenvolvimento de conceito e execução visual de forma mais intencional.', gallery: ['/projects/femtolab/slide-1.png', '/projects/femtolab/slide-2.png', '/projects/femtolab/slide-3.png', '/projects/femtolab/slide-4.png', '/projects/femtolab/slide-5.png', '/projects/femtolab/slide-6.png', '/projects/femtolab/slide-7.png', '/projects/femtolab/slide-8.png'] },
  ],
};

const currentProjects = projectData.en;
const sectionLabels = {
  all: { en: 'All', pt: 'Todos' },
  favorites: { en: 'Favorites', pt: 'Favoritos' },
  uiux: { en: 'UI & UX', pt: 'UI & UX' },
  'design-systems': { en: 'Design Systems', pt: 'Sistemas de Design' },
  branding: { en: 'Branding', pt: 'Branding' },
};

function ProjectsWindow() {
  const { t, language } = useLanguage();
  const [currentProjects, setCurrentProjects] = useState(projectData.en);
  const [history, setHistory] = useState(() => [
    { path: ['My Projects', 'Projects'], section: 'all', expanded: null }
  ]);
  const [historyIndex, setHistoryIndex] = useState(0);

  useEffect(() => {
    setCurrentProjects(projectData[language] || projectData.en);
  }, [language]);

  useEffect(() => {
    if (history.length === 1 && history[0].path[0] === 'My Projects') {
      setHistory([{ path: [t('myProjects'), t('projects')], section: 'all', expanded: null }]);
    }
  }, [language]);

  const currentState = history[historyIndex];
  const currentPath = currentState.path;
  const selectedSection = currentState.section;
  const expandedSection = currentState.expanded;
  const currentProjectId = currentState.projectId;

  const getProjectById = (id) => currentProjects.find(p => p.id === id);
  const currentProject = currentProjectId ? getProjectById(currentProjectId) : null;

  const canGoBack = historyIndex > 0;
  const canGoForward = historyIndex < history.length - 1;

  const goBack = () => {
    if (historyIndex > 0) {
      setHistoryIndex(historyIndex - 1);
    }
  };

  const goForward = () => {
    if (historyIndex < history.length - 1) {
      setHistoryIndex(historyIndex + 1);
    }
  };

  const navigateToBreadcrumb = (index) => {
    if (index >= 0 && index <= historyIndex) {
      setHistoryIndex(index);
    }
  };

  const handleProjectClick = (projectId) => {
    const project = currentProjects.find(p => p.id === projectId);
    if (!project) return;

    const newPath = [...currentPath, project.name];

    const newState = {
      path: newPath,
      section: selectedSection,
      expanded: expandedSection,
      projectId: project.id
    };

    const newHistory = history.slice(0, historyIndex + 1);
    newHistory.push(newState);
    setHistory(newHistory);
    setHistoryIndex(newHistory.length - 1);
  };

  const [currentSlide, setCurrentSlide] = useState(0);
  
  useEffect(() => {
    setCurrentSlide(0);
  }, [currentProjectId]);

  const galleryImages = currentProject?.gallery || [];
  const totalSlides = galleryImages.length || 3;

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % totalSlides);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
  };

  const getSectionLabel = (key) => {
    return sectionLabels[key]?.[language] || key;
  };

  const displayedProjects = useMemo(() => {
    if (expandedSection) {
      return currentProjects.filter(p => p.category === expandedSection);
    }
    if (selectedSection === 'all') {
      return currentProjects;
    }
    if (selectedSection === 'favorites') {
      return currentProjects.filter(p => p.isFavorite);
    }
    return currentProjects;
  }, [currentProjects, expandedSection, selectedSection]);

  const currentSlideImage = useMemo(() => {
    if (!galleryImages.length) return null;
    return galleryImages[currentSlide];
  }, [galleryImages, currentSlide]);

  const handleSectionClick = (sectionKey, hasChevron = false) => {
    if (!hasChevron && sectionKey === selectedSection && !currentProjectId) return;
    
    let newExpanded = null;
    let newSection = sectionKey;
    
    if (hasChevron) {
      newExpanded = expandedSection === sectionKey ? null : sectionKey;
      newSection = selectedSection;
    }
    
    const newPath = hasChevron && newExpanded
      ? [t('myProjects'), t('projects'), getSectionLabel(sectionKey)]
      : hasChevron && !newExpanded
        ? [t('myProjects'), t('projects')]
        : [t('myProjects'), t('projects'), getSectionLabel(sectionKey)];
    
    const newState = {
      path: newPath,
      section: newSection,
      expanded: newExpanded,
      projectId: null
    };
    
    const newHistory = history.slice(0, historyIndex + 1);
    newHistory.push(newState);
    setHistory(newHistory);
    setHistoryIndex(newHistory.length - 1);
  };

  return (
    <div className="projects-window">
      <div className="projects-navigation">
        <div className="nav-arrows">
          <button 
            className="nav-arrow" 
            onClick={goBack}
            disabled={historyIndex <= 0}
            title="Voltar"
          >
            <CaretLeft size={20} weight="bold" />
          </button>
          <button 
            className="nav-arrow" 
            onClick={goForward}
            disabled={historyIndex >= history.length - 1}
            title="Avançar"
          >
            <CaretRight size={20} weight="bold" />
          </button>
        </div>
        <div className="breadcrumb">
          <Folder size={18} weight="fill" className="breadcrumb-icon" />
          {currentPath.map((step, index) => (
            <span key={index}>
              {index > 0 && <span className="breadcrumb-sep">›</span>}
              <button 
                className="breadcrumb-step clickable"
                onClick={() => navigateToBreadcrumb(index)}
              >
                {step}
              </button>
            </span>
          ))}
        </div>
      </div>
      
      <div className="projects-body">
        <div className="projects-sidebar">
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${selectedSection === 'all' && !expandedSection ? 'selected' : ''}`}
              onClick={() => handleSectionClick('all', false)}
            >
              <Folder size={18} weight="fill" className="button-icon" />
              <span className="button-label">{t('all') || 'All'}</span>
            </div>
            <div 
              className={`sidebar-button ${selectedSection === 'favorites' && !expandedSection ? 'selected' : ''}`}
              onClick={() => handleSectionClick('favorites', false)}
            >
              <Star size={18} weight="fill" className="button-icon" />
              <span className="button-label">{t('favorites') || 'Favorites'}</span>
            </div>
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'uiux' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('uiux', true)}
            >
              <Devices size={18} weight="fill" className="button-icon" />
              <span className="button-label">UI & UX</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'uiux' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'uiux' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'uiux').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'design-systems' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('design-systems', true)}
            >
              <Books size={18} weight="fill" className="button-icon" />
              <span className="button-label">Design Systems</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'design-systems' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'design-systems' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'design-systems').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'branding' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('branding', true)}
            >
              <PenNib size={18} weight="fill" className="button-icon" />
              <span className="button-label">Branding</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'branding' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'branding' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'branding').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
        
        <div className="projects-thumbnails">
          {currentProject ? (
            <div className="project-detail">
              <div className="project-detail-header">
                <div className="project-detail-image">
                  {currentProject.image ? (
                    <img src={currentProject.image} alt={currentProject.name} loading="lazy" />
                  ) : (
                    <div className="project-detail-image-placeholder"></div>
                  )}
                </div>
                <div className="project-detail-info">
                  <h2 className="project-detail-name">{currentProject.name}</h2>
                  <p className="project-detail-context">{currentProject.context || 'No description available.'}</p>
                  <p className="project-detail-role">
                    <strong>{t('myRole') || 'My Role'}:</strong> {currentProject.role || 'No role description available.'}
                  </p>
                  {currentProject.link && (
                    <a href={currentProject.link} target="_blank" rel="noopener noreferrer" className="project-link">
                      {t('projectLink') || 'View Project'} →
                    </a>
                  )}
                </div>
              </div>
              
              <div className="project-detail-sections">
                  <div className="project-section">
                    <h3 className="project-section-title">{t('designChallenge') || 'Design Challenge'}</h3>
                    <p className="project-section-text">
                      <strong>Challenge:</strong> {currentProject.problem || 'No challenge description available.'}<br /><br />
                      <strong>Outcome:</strong> {currentProject.result || 'No outcome description available.'}
                    </p>
                  </div>
                </div>
                
                <div className="project-detail-gallery">
                  <h3 className="gallery-title">{t('projectPresentation') || 'Project Presentation'}</h3>
                  {galleryImages.length > 0 ? (
                    <div className="gallery-carousel">
                      <button className="gallery-nav gallery-prev" onClick={prevSlide} disabled={galleryImages.length <= 1}>
                        <PrevIcon size={24} weight="bold" />
                      </button>
                      <div className="gallery-slide">
                        {galleryImages[currentSlide].startsWith('#') ? (
                          <div className="gallery-color-slide" style={{ backgroundColor: galleryImages[currentSlide] }}></div>
                        ) : (
                          <img src={galleryImages[currentSlide]} alt={`Slide ${currentSlide + 1}`} loading="lazy" />
                        )}
                      </div>
                      <button className="gallery-nav gallery-next" onClick={nextSlide} disabled={galleryImages.length <= 1}>
                        <NextIcon size={24} weight="bold" />
                      </button>
                    </div>
                  ) : (
                    <div className="gallery-placeholder"></div>
                  )}
                  {galleryImages.length > 0 && (
                    <>
                      <div className="gallery-counter">
                        {currentSlide + 1} / {galleryImages.length}
                      </div>
                      <div className="gallery-thumbnails">
                        {galleryImages.map((img, idx) => (
                          <button 
                            key={idx} 
                            className={`gallery-thumb ${idx === currentSlide ? 'active' : ''}`}
                            onClick={() => setCurrentSlide(idx)}
                          >
                            {img.startsWith('#') ? (
                              <div className="gallery-thumb-color" style={{ backgroundColor: img }}></div>
                            ) : (
                              <img src={img} alt={`Thumb ${idx + 1}`} loading="lazy" />
                            )}
                          </button>
                        ))}
                      </div>
                    </>
                  )}
                </div>

                <div className="project-section">
                  <h3 className="project-section-title">{t('lessonsLearned') || 'Lessons Learned'}</h3>
                  <p className="project-section-text">{currentProject.lessons || 'No lessons learned available.'}</p>
                </div>
            </div>
          ) : (
            <div className="thumbnails-grid">
              {displayedProjects.map((project) => (
                <div key={project.id} className="thumbnail-card" onClick={() => handleProjectClick(project.id)}>
                  <div className="thumbnail-image">
                    {project.image ? (
                      <img src={project.image} alt={project.name} />
                    ) : null}
                  </div>
                  <span className="thumbnail-name">{project.name}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      
      <div className="projects-footer">
        <Folders size={20} weight="fill" className="footer-icon" />
        <span className="footer-count">{displayedProjects.length} {t('items')}</span>
      </div>
    </div>
  );
}

export default ProjectsWindow;