import { useState, useEffect, useMemo, useCallback } from 'react';
import { CaretLeft, CaretRight, Folder, Folders, Star, Devices, Books, PenNib, CaretDown, CaretRight as NextIcon, CaretLeft as PrevIcon } from '@phosphor-icons/react';
import { useLanguage } from '../../i18n/LanguageContext';
import './ProjectsWindow.css';

const projectData = {
  en: [
    { id: 1, name: 'Atomic Design System', category: 'design-systems', isFavorite: true, image: '/projects/atomic-design-system/thumbnail.png', context: 'Development of an Atomic Design-based Design System, with creation of tokens, reusable components and structuring of a React library. The project aimed to accelerate the front-end team\'s work, reduce inconsistencies between products and strengthen collaboration between design and engineering. To develop the components, MiniMax 2.5 was used in OpenCode.', link: 'https://github.com/ThiagoJezini/Web_Design_Atomic', problem: 'The design challenge was developing a scalable design system that could unify visual standards across multiple products while still being flexible enough to accommodate future needs. The goal was to reduce development time, eliminate inconsistencies, and improve collaboration between design and engineering teams through a shared component library.', role: 'Design team leader', result: 'The library was widely adopted and expanded with additional components to cover emerging project needs. Development time was significantly reduced, and visual consistency improved across all products. The system became the single source of truth for design and enabled faster iteration cycles.', lessons: 'In this project, the main learning was more technical, especially about how AI can be implemented to enhance and optimize human productivity without replacing peoples role in the process. It was an important experience to understand AI as a support tool: capable of automating steps, accelerating analyses, and facilitating decisions, but always keeping the user as a central part of the workflow.', gallery: ['/projects/atomic-design-system/slide-1.png', '/projects/atomic-design-system/slide-2.png', '/projects/atomic-design-system/slide-3.png', '/projects/atomic-design-system/slide-4.png', '/projects/atomic-design-system/slide-5.png'] },
    { id: 2, name: 'BPMS', category: 'uiux', isFavorite: false, image: '/projects/bpms/thumbnail.png', context: 'The BPMS project is aimed at digitizing the process in which it is named (Business Process Management Suite). Initially made to order, it was thought in its development to become an end product that could be used by companies in business management and internal production.', link: '', problem: 'The design challenge was creating a system capable of transforming BPMS-based production flows into clear KPIs and actionable metrics. The goal was to help the company track performance, identify bottlenecks, and understand production efficiency without overwhelming users with complex operational data. The main focus was organizing information in a way that respected the actual structure of the company processes, but that still made dashboards, indicators, and analysis tools simple enough to support quick decisions.', role: 'Product Designer and UI & UX Designer, working directly on controlling and deliveries of the development team.', result: 'The product was delivered successfully, allowing the contractor to track their KPIs more clearly and identify production bottlenecks based on data generated by the BPMS flow itself. With this, the company gained a more strategic view of the operation, facilitating performance analysis and decision-making. In addition to meeting the internal project needs, the final system was consolidated as a scalable solution and began to be offered as a product to other company clients.', lessons: 'This was the project where I had the most creative and organizational freedom, which allowed me to participate more strategically in product and process decisions. In addition to technical learning, it was an important experience to better understand how to organize demands, align expectations, and conduct work more autonomously. I also learned a lot about people management, especially about how to deal with different professional profiles. I understood that each person has their own way of working, communicating, and solving problems, and that recognizing these differences is essential to creating a healthier, more collaborative, and efficient workflow.', gallery: ['/projects/bpms/slide-1.png', '/projects/bpms/slide-2.png', '/projects/bpms/slide-3.png', '/projects/bpms/slide-4.png', '/projects/bpms/slide-5.png', '/projects/bpms/slide-6.png', '/projects/bpms/slide-7.png'] },
  ],
  pt: [
    { id: 1, name: 'Atomic Design System', category: 'design-systems', isFavorite: true, image: '/projects/atomic-design-system/thumbnail.png', context: 'Development of an Atomic Design-based Design System, with creation of tokens, reusable components and structuring of a React library. The project aimed to accelerate the front-end team\'s work, reduce inconsistencies between products and strengthen collaboration between design and engineering. To develop the components, MiniMax 2.5 was used in OpenCode.', link: 'https://github.com/ThiagoJezini/Web_Design_Atomic', problem: 'O desafio de design foi desenvolver um design system escalável que pudesse unificar os padrões visuais entre múltiplos produtos, mas que ainda fosse flexível o bastante para acomodar necessidades futuras. O objetivo era reduzir o tempo de desenvolvimento, eliminar inconsistências e melhorar a colaboração entre as equipes de design e engenharia através de uma biblioteca de componentes compartilhada.', role: 'Líder da equipe de design', result: 'A biblioteca foi amplamente adotada e expandida com componentes adicionais para cobrir as necessidades dos projetos que surgiram. O tempo de desenvolvimento foi significativamente reduzido e a consistência visual melhorou em todos os produtos. O sistema se tornou a única fonte de verdade para design e permitiu ciclos de iteração mais rápidos.', lessons: 'In this project, the main learning was more technical, especially about how AI can be implemented to enhance and optimize human productivity without replacing peoples role in the process. It was an important experience to understand AI as a support tool: capable of automating steps, accelerating analyses, and facilitating decisions, but always keeping the user as a central part of the workflow.', gallery: ['/projects/atomic-design-system/slide-1.png', '/projects/atomic-design-system/slide-2.png', '/projects/atomic-design-system/slide-3.png', '/projects/atomic-design-system/slide-4.png', '/projects/atomic-design-system/slide-5.png'] },
    { id: 2, name: 'BPMS', category: 'uiux', isFavorite: false, image: '/projects/bpms/thumbnail.png', context: 'O projeto BPMS é voltado para digitalizar o processo na qual é nomeado (Business Process Management Suite). Inicialmente feito sob encomenda, foi pensado em seu desenvolvimento a tornar-se um produto final que pudesse ser utilizado por empresas no gerenciamento de negócios e produção interna.', link: '', problem: 'O desafio de design foi criar um sistema capaz de transformar os fluxos de produção baseados em BPMS em KPIs claros e métricas acionáveis. O objetivo era ajudar a empresa a acompanhar performance, identificar gargalos e entender a eficiência da produção sem sobrecarregar os usuários com dados operacionais complexos. O foco principal foi organizar as informações de uma forma que respeitasse a estrutura real dos processos da empresa, mas que ainda tornasse dashboards, indicadores e ferramentas de análise simples o suficiente para apoiar decisões rápidas.', role: 'Product Designer e UI & UX Designer, trabalhando diretamente no controle de atividades e entregas do time de desenvolvimento.', result: 'O produto foi entregue com sucesso, permitindo que o contratante acompanhasse seus KPIs com mais clareza e identificasse gargalos de produção com base nos dados gerados pelo próprio fluxo BPMS. Com isso, a empresa passou a ter uma visão mais estratégica da operação, facilitando a análise de desempenho e a tomada de decisão. Além de atender às necessidades internas do projeto, o sistema final se consolidou como uma solução escalável e passou a ser oferecido como produto para outros clientes da empresa.', lessons: 'Esse foi o projeto em que tiver mais liberdade criativa e organizacional, o que me permitiu participar de forma mais estratégica das decisões de produto e processo. Além do aprendizado técnico, foi uma experiência importante para entender melhor como organizar demandas, alinhar expectativas e conduzir o trabalho de forma mais autônoma. Também aprendi muito sobre gestão de pessoas, principalmente sobre como lidar com diferentes perfis profissionais. Entendi que cada pessoa tem sua própria forma de trabalhar, se comunicar e resolver problemas, e que reconhecer essas diferenças é essencial para criar um fluxo de trabalho mais saudável, colaborativo e eficiente.', gallery: ['/projects/bpms/slide-1.png', '/projects/bpms/slide-2.png', '/projects/bpms/slide-3.png', '/projects/bpms/slide-4.png', '/projects/bpms/slide-5.png', '/projects/bpms/slide-6.png', '/projects/bpms/slide-7.png'] },
  ],
};

const currentProjects = projectData.en;
const sectionLabels = {
  all: { en: 'All', pt: 'Todos' },
  favorites: { en: 'Favorites', pt: 'Favoritos' },
  uiux: { en: 'UI & UX', pt: 'UI & UX' },
  'design-systems': { en: 'Design Systems', pt: 'Sistemas de Design' },
  branding: { en: 'Branding', pt: 'Branding' },
};

function ProjectsWindow() {
  const { t, language } = useLanguage();
  const [currentProjects, setCurrentProjects] = useState(projectData.en);
  const [history, setHistory] = useState(() => [
    { path: ['My Projects', 'Projects'], section: 'all', expanded: null }
  ]);
  const [historyIndex, setHistoryIndex] = useState(0);

  useEffect(() => {
    setCurrentProjects(projectData[language] || projectData.en);
  }, [language]);

  useEffect(() => {
    if (history.length === 1 && history[0].path[0] === 'My Projects') {
      setHistory([{ path: [t('myProjects'), t('projects')], section: 'all', expanded: null }]);
    }
  }, [language]);

  const currentState = history[historyIndex];
  const currentPath = currentState.path;
  const selectedSection = currentState.section;
  const expandedSection = currentState.expanded;
  const currentProjectId = currentState.projectId;

  const getProjectById = (id) => currentProjects.find(p => p.id === id);
  const currentProject = currentProjectId ? getProjectById(currentProjectId) : null;

  const canGoBack = historyIndex > 0;
  const canGoForward = historyIndex < history.length - 1;

  const goBack = () => {
    if (historyIndex > 0) {
      setHistoryIndex(historyIndex - 1);
    }
  };

  const goForward = () => {
    if (historyIndex < history.length - 1) {
      setHistoryIndex(historyIndex + 1);
    }
  };

  const navigateToBreadcrumb = (index) => {
    if (index >= 0 && index <= historyIndex) {
      setHistoryIndex(index);
    }
  };

  const handleProjectClick = (projectId) => {
    const project = currentProjects.find(p => p.id === projectId);
    if (!project) return;

    const newPath = [...currentPath, project.name];

    const newState = {
      path: newPath,
      section: selectedSection,
      expanded: expandedSection,
      projectId: project.id
    };

    const newHistory = history.slice(0, historyIndex + 1);
    newHistory.push(newState);
    setHistory(newHistory);
    setHistoryIndex(newHistory.length - 1);
  };

  const [currentSlide, setCurrentSlide] = useState(0);
  
  useEffect(() => {
    setCurrentSlide(0);
  }, [currentProjectId]);

  const galleryImages = currentProject?.gallery || [];
  const totalSlides = galleryImages.length || 3;

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % totalSlides);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
  };

  const getSectionLabel = (key) => {
    return sectionLabels[key]?.[language] || key;
  };

  const displayedProjects = useMemo(() => {
    if (expandedSection) {
      return currentProjects.filter(p => p.category === expandedSection);
    }
    if (selectedSection === 'all') {
      return currentProjects;
    }
    if (selectedSection === 'favorites') {
      return currentProjects.filter(p => p.isFavorite);
    }
    return currentProjects;
  }, [currentProjects, expandedSection, selectedSection]);

  const currentSlideImage = useMemo(() => {
    if (!galleryImages.length) return null;
    return galleryImages[currentSlide];
  }, [galleryImages, currentSlide]);

  const handleSectionClick = (sectionKey, hasChevron = false) => {
    if (!hasChevron && sectionKey === selectedSection && !currentProjectId) return;
    
    let newExpanded = null;
    let newSection = sectionKey;
    
    if (hasChevron) {
      newExpanded = expandedSection === sectionKey ? null : sectionKey;
      newSection = selectedSection;
    }
    
    const newPath = hasChevron && newExpanded
      ? [t('myProjects'), t('projects'), getSectionLabel(sectionKey)]
      : hasChevron && !newExpanded
        ? [t('myProjects'), t('projects')]
        : [t('myProjects'), t('projects'), getSectionLabel(sectionKey)];
    
    const newState = {
      path: newPath,
      section: newSection,
      expanded: newExpanded,
      projectId: null
    };
    
    const newHistory = history.slice(0, historyIndex + 1);
    newHistory.push(newState);
    setHistory(newHistory);
    setHistoryIndex(newHistory.length - 1);
  };

  return (
    <div className="projects-window">
      <div className="projects-navigation">
        <div className="nav-arrows">
          <button 
            className="nav-arrow" 
            onClick={goBack}
            disabled={historyIndex <= 0}
            title="Voltar"
          >
            <CaretLeft size={20} weight="bold" />
          </button>
          <button 
            className="nav-arrow" 
            onClick={goForward}
            disabled={historyIndex >= history.length - 1}
            title="Avançar"
          >
            <CaretRight size={20} weight="bold" />
          </button>
        </div>
        <div className="breadcrumb">
          <Folder size={18} weight="fill" className="breadcrumb-icon" />
          {currentPath.map((step, index) => (
            <span key={index}>
              {index > 0 && <span className="breadcrumb-sep">›</span>}
              <button 
                className="breadcrumb-step clickable"
                onClick={() => navigateToBreadcrumb(index)}
              >
                {step}
              </button>
            </span>
          ))}
        </div>
      </div>
      
      <div className="projects-body">
        <div className="projects-sidebar">
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${selectedSection === 'all' && !expandedSection ? 'selected' : ''}`}
              onClick={() => handleSectionClick('all', false)}
            >
              <Folder size={18} weight="fill" className="button-icon" />
              <span className="button-label">{t('all') || 'All'}</span>
            </div>
            <div 
              className={`sidebar-button ${selectedSection === 'favorites' && !expandedSection ? 'selected' : ''}`}
              onClick={() => handleSectionClick('favorites', false)}
            >
              <Star size={18} weight="fill" className="button-icon" />
              <span className="button-label">{t('favorites') || 'Favorites'}</span>
            </div>
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'uiux' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('uiux', true)}
            >
              <Devices size={18} weight="fill" className="button-icon" />
              <span className="button-label">UI & UX</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'uiux' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'uiux' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'uiux').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'design-systems' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('design-systems', true)}
            >
              <Books size={18} weight="fill" className="button-icon" />
              <span className="button-label">Design Systems</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'design-systems' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'design-systems' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'design-systems').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
          
          <div className="sidebar-section">
            <div 
              className={`sidebar-button ${expandedSection === 'branding' ? 'selected' : ''}`}
              onClick={() => handleSectionClick('branding', true)}
            >
              <PenNib size={18} weight="fill" className="button-icon" />
              <span className="button-label">Branding</span>
              <CaretDown size={14} weight="bold" className={`button-chevron ${expandedSection === 'branding' ? 'rotated' : ''}`} />
            </div>
            {expandedSection === 'branding' && (
              <div className="sidebar-submenu">
                {currentProjects.filter(p => p.category === 'branding').map((project) => (
                  <div key={project.id} className="sidebar-subitem">
                    <Folder size={16} weight="fill" className="subitem-icon" />
                    <span className="subitem-label">{project.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
        
        <div className="projects-thumbnails">
          {currentProject ? (
            <div className="project-detail">
              <div className="project-detail-header">
                <div className="project-detail-image">
                  {currentProject.image ? (
                    <img src={currentProject.image} alt={currentProject.name} loading="lazy" />
                  ) : (
                    <div className="project-detail-image-placeholder"></div>
                  )}
                </div>
                <div className="project-detail-info">
                  <h2 className="project-detail-name">{currentProject.name}</h2>
                  <p className="project-detail-context">{currentProject.context || 'No description available.'}</p>
                  <p className="project-detail-role">
                    <strong>{t('myRole') || 'My Role'}:</strong> {currentProject.role || 'No role description available.'}
                  </p>
                  {currentProject.link && (
                    <a href={currentProject.link} target="_blank" rel="noopener noreferrer" className="project-link">
                      {t('projectLink') || 'View Project'} →
                    </a>
                  )}
                </div>
              </div>
              
              <div className="project-detail-sections">
                  <div className="project-section">
                    <h3 className="project-section-title">{t('designChallenge') || 'Design Challenge'}</h3>
                    <p className="project-section-text">
                      <strong>Challenge:</strong> {currentProject.problem || 'No challenge description available.'}<br /><br />
                      <strong>Outcome:</strong> {currentProject.result || 'No outcome description available.'}
                    </p>
                  </div>
                </div>
                
                <div className="project-detail-gallery">
                  <h3 className="gallery-title">{t('projectPresentation') || 'Project Presentation'}</h3>
                  {galleryImages.length > 0 ? (
                    <div className="gallery-carousel">
                      <button className="gallery-nav gallery-prev" onClick={prevSlide} disabled={galleryImages.length <= 1}>
                        <PrevIcon size={24} weight="bold" />
                      </button>
                      <div className="gallery-slide">
                        {galleryImages[currentSlide].startsWith('#') ? (
                          <div className="gallery-color-slide" style={{ backgroundColor: galleryImages[currentSlide] }}></div>
                        ) : (
                          <img src={galleryImages[currentSlide]} alt={`Slide ${currentSlide + 1}`} loading="lazy" />
                        )}
                      </div>
                      <button className="gallery-nav gallery-next" onClick={nextSlide} disabled={galleryImages.length <= 1}>
                        <NextIcon size={24} weight="bold" />
                      </button>
                    </div>
                  ) : (
                    <div className="gallery-placeholder"></div>
                  )}
                  {galleryImages.length > 0 && (
                    <>
                      <div className="gallery-counter">
                        {currentSlide + 1} / {galleryImages.length}
                      </div>
                      <div className="gallery-thumbnails">
                        {galleryImages.map((img, idx) => (
                          <button 
                            key={idx} 
                            className={`gallery-thumb ${idx === currentSlide ? 'active' : ''}`}
                            onClick={() => setCurrentSlide(idx)}
                          >
                            {img.startsWith('#') ? (
                              <div className="gallery-thumb-color" style={{ backgroundColor: img }}></div>
                            ) : (
                              <img src={img} alt={`Thumb ${idx + 1}`} loading="lazy" />
                            )}
                          </button>
                        ))}
                      </div>
                    </>
                  )}
                </div>

                <div className="project-section">
                  <h3 className="project-section-title">{t('lessonsLearned') || 'Lessons Learned'}</h3>
                  <p className="project-section-text">{currentProject.lessons || 'No lessons learned available.'}</p>
                </div>
            </div>
          ) : (
            <div className="thumbnails-grid">
              {displayedProjects.map((project) => (
                <div key={project.id} className="thumbnail-card" onClick={() => handleProjectClick(project.id)}>
                  <div className="thumbnail-image">
                    {project.image ? (
                      <img src={project.image} alt={project.name} />
                    ) : null}
                  </div>
                  <span className="thumbnail-name">{project.name}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      
      <div className="projects-footer">
        <Folders size={20} weight="fill" className="footer-icon" />
        <span className="footer-count">{displayedProjects.length} {t('items')}</span>
      </div>
    </div>
  );
}

export default ProjectsWindow;